# Services for the Job Analytics Platform
services:
  # PostgreSQL database for kestra
  postgres:
    image: postgres:latest
    container_name: kestra-db
    pull_policy: if_not_present
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - job-analytics-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  # Metabase for dashboards
  metabase:
    image: metabase/metabase:latest
    platform: linux/amd64 # Specify platform for Apple Silicon compatibility
    container_name: job-analytics-metabase
    pull_policy: if_not_present
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=jobanalytics
      - MB_DB_PASS=jobanalytics
      - MB_DB_HOST=postgres
      - MB_JETTY_PORT=3000
      - JAVA_OPTS=-Xmx2g
      - MB_ENCRYPTION_SECRET_KEY=a7ca41bfd7b8476b9c77e3a9e698d541f7de1d32d38246728328ab409e3ef6f3
    ports:
      - "3000:3000"
    networks:
      - job-analytics-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Kestra for workflow orchestration
  kestra:
    image: kestra/kestra:latest # Use the latest stable version, DO NOT CHANGE
    platform: linux/amd64 # Specify platform for Apple Silicon compatibility
    container_name: job-analytics-kestra
    pull_policy: if_not_present
    command: server standalone
    user: "root"
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      # - ./flows:/app/flows # Mount local flows for easy import in dev
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
          tutorialFlows:
            enabled: false
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - job-analytics-network
    depends_on:
      postgres:
        condition: service_started

  # Postgres for database
  pgdatabase:
    image: postgres:latest
    container_name: job-analytics-pgdatabase
    pull_policy: if_not_present
    environment:
      POSTGRES_DB: jobanalytics_data
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./jobs_postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    networks:
      - job-analytics-network

  metabase_db:
    image: postgres:latest
    container_name: metabase-db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: jobanalytics
      POSTGRES_PASSWORD: jobanalytics
    volumes:
      - metabase_db_data:/var/lib/postgresql/data
    networks:
      - job-analytics-network

  # Python service for running scripts
  python:
    build:
      context: ..
      dockerfile: 01_local/Dockerfile.python
    container_name: job-analytics-python
    volumes:
      - ..:/app
    networks:
      - job-analytics-network
    depends_on:
      postgres:
        condition: service_healthy
    command: "tail -f /dev/null" # Keep container running

networks:
  job-analytics-network:
    name: job-analytics-network

volumes:
  postgres_data:
    name: job-analytics-postgres-data
  kestra_data:
    name: job-analytics-kestra-data
  metabase_db_data:
    name: job-analytics-metabase-db-data
